trigger: none

pool:
 vmImage: 'ubuntu-latest'

stages:
 - stage: 'Build'
   jobs:
    - job: 'installandbuild'
      steps:
           
      - task: Npm@1
        inputs:
         command: 'install'
         workingDir: '$(System.DefaultWorkingDirectory)'
        
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(System.DefaultWorkingDirectory)'
          customCommand: 'run build'