trigger: none

pool:
 vmImage: 'ubuntu-latest'

stages:
 - stage: 'Build'
   jobs:
    - job: 'install-build'
      steps:
           
      - task: Npm@1
        inputs:
         command: 'install'
         workingDir: 'AngularApp/src'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'AngularApp/src'
          customCommand: 'run build'