trigger: none

pool:
 vmImage: 'ubuntu-latest'

stages:
 - stage: 'Build'
   jobs:
    - job: 'Build'
      steps:
      - task: NodeTool@0
        inputs:
         versionSpec: '18.x'  # Use the version of Node.js required for your Angular app
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'install -g @angular/cli'
        displayName: 'Install Angular CLI'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(System.DefaultWorkingDirectory)/angularapp'
        displayName: 'Install project dependencies'

      - task: CmdLine@2
        inputs:
          script: 'ng build --configuration=production'
          workingDirectory: '$(System.DefaultWorkingDirectory)/angularapp'
        displayName: 'Build Angular app'
       
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/angularapp/dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/angular-app.zip'

      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'angular-app' 
         